# Text Analysis: An Introduction

In [3]:
import nltk    # For sentiment analysis
import pandas  # For data manipulation
import seaborn # For data visualisation

from corpus import import_corpus

In [8]:
from IPython.display import IFrame
IFrame(src="https://www.youtube.com/embed/oP3c1h8v2ZQ?si=Nj-dhPMtRNeL2-vO", width=560, height=315)

In [6]:
corpus = import_corpus(
    corpus_dir="data",    # The books are in the data/ directory
    tokenise_by="word",   # Split each book into individual words
    clean_gutenberg=True, # Remove gutenberg licence from start and end
    to_lower=True         # Put all words in lower case
)

Loading data/manifest.csv ...
5 texts found in data/manifest.csv. Importing with the following settings:
TextImporter(corpus_dir='data', to_lower=True, tokenise_by='word', clean_gutenberg=True remove_punctuation=False, to_stems=False, stopwords=None)
Reading data/alice-in-wonderland.txt ...
Reading data/frankenstein.txt ...
Reading data/moby-dick.txt ...
Reading data/pride-and-prejudice.txt ...
Reading data/don-quixote.txt ...
Done!

In [7]:
corpus

,title,author,date,file_name,tokens
0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,"[[, illustration, ], alice, ’, s, adventures, ..."
1,"Frankenstein; or, the Modern Prometheus",Mary Shelley,1818,frankenstein.txt,"[frankenstein, ;, or, ,, the, modern, promethe..."
2,"Moby Dick; or, The Whale",Herman Melville,1851,moby-dick.txt,"[moby-dick, ;, or, ,, the, whale, ., by, herma..."
3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,"[[, illustration, :, george, allen, publisher,..."
4,Don Quixote,Miguel Cervantes de Saavedra,1615,don-quixote.txt,"[bookcover.jpg, full, size, spine.jpg, (, 152k..."

#### Lab Exercise 0: "Tidy" the textual corpus

Complete the function below to tidy this week's corpus. In the end, there should be one row per sentence.

1. Use [the `.explode()` method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.explode.html) to "unnest" or "explode" the `"tokens"` column.
2. Use [the `.reset_index()` method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html) to create a unique row index, and move the non-unique index to a new column called `"novel_index"`.
3. Use [the `.groupby()` method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) and [the `.cumcount()` method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.typing.DataFrameGroupBy.cumcount.html) to create a `"sentence_index"` column.

As with other `import_` functions this term, the function has *no input*. It is for importing a fixed dataset into a research document, so it doesn't need to vary with multiple inputs.

In [10]:
def import_sentiment_analysis_corpus(verbose=2):
    """Import the sentiment analysis corpus from the "data" directory,
    tokenising by sentence.
    
    NB: This function has no input. The "data" directory is hard-coded
    as the location of the corpus."""

    # Import the corpus in the "data" folder, tokenising by sentence
    # Problem: the `tokens` column is a `list`-column, which isn't very useful...
    corpus = import_corpus(corpus_dir="data", tokenise_by="sent", verbose=verbose)

    # Explode the "tokens" column
    ### BEGIN SOLUTION
    tidy_corpus = corpus.explode("tokens")
    ### END SOLUTION
    
    # Reset the index, storing the old row index in a new column called "novel_index"
    ### BEGIN SOLUTION
    tidy_corpus = tidy_corpus.reset_index(names="novel_index")
    ### END SOLUTION

    # Create the "sentence_index" column using .groupby() and .cumcount()
    ### BEGIN SOLUTION
    tidy_corpus = tidy_corpus.assign(sentence_index = tidy_corpus.groupby("title").cumcount())
    ### END SOLUTION

    # Return!
    return tidy_corpus

In [11]:
# Expected output:
tidy_corpus = import_sentiment_analysis_corpus()
display(tidy_corpus)

# Tests
assert isinstance(tidy_corpus, pd.DataFrame) # Did you return a data frame of the corpus?
assert tidy_corpus.shape[0] == 17707 # Did you tokenise it correctly? Did you explode it?
assert tidy_corpus.shape[1] >= 6 # Did you reset the index?
assert "novel_index" in tidy_corpus.columns # Did you use the 'names' parameter in .reset_index?
assert tidy_corpus.shape[1] == 7 # Did you remember to count the number of sentences in each novel?
assert "sentence_index" in tidy_corpus.columns # Did you call the new column "sentence_index"?
print("\nAll tests passed!")

Loading data/manifest.csv ...
4 texts found in data/manifest.csv. Importing with the following settings:
TextImporter(corpus_dir='data', to_lower=True, tokenise_by='sent', clean_gutenberg=True remove_punctuation=False, to_stems=False, stopwords=None)
Reading data/alice-in-wonderland.txt ...
Reading data/frankenstein.txt ...
Reading data/moby-dick.txt ...
Reading data/pride-and-prejudice.txt ...
Done!

,novel_index,title,author,date,file_name,tokens,sentence_index
0,0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,\n\n[illustration]\n\n\n\n\nalice’s adventures...,0
1,0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,the pool of tears\n chapter iii.,1
2,0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,a caucus-race and a long tale\n chapter iv.,2
3,0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,the rabbit sends in a little bill\n chapter v....,3
4,0,Alice in Wonderland,Lewis Carroll,1865,alice-in-wonderland.txt,pig and pepper\n chapter vii.,4
...,...,...,...,...,...,...,...
17702,3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,lady catherine was extremely indignant on the ...,4839
17703,3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,"but at length, by elizabeth’s persuasion,\nhe ...",4840
17704,3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,with the gardiners they were always on the mos...,4841
17705,3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,"darcy,\nas well as elizabeth, really loved the...",4842
17706,3,Pride and Prejudice,Jane Austen,1813,pride-and-prejudice.txt,[illustration:\n\n ...,4843

All tests passed!